FROM python:3.12.2-alpine

# Set the working directory
WORKDIR /app

# Copy the Flask application into the container
COPY job-pair-backend/ /job-pair-backend

# Install dependencies
RUN pip install -r /job-pair-backend/requirements.txt

# Expose the port the app runs on
EXPOSE 5000

CMD ["python", "/job-pair-backend/dummy_backend.py"]