FROM python:3.12.2-alpine

# Set the working directory
WORKDIR /app

# Copy the Flask application into the container
COPY job-pair-backend/ /app

# Install dependencies
RUN pip install -r requirements.txt

# Expose the port the app runs on
EXPOSE 5000

CMD ["python", "dummy_backend.py"]